services:
  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_DB: albaranes
      POSTGRES_USER: lupierra
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
