# Generated by Django 3.2.19 on 2023-06-20 20:32

from django.db import migrations
import lupanes.users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', lupanes.users.models.UserManager()),
            ],
        ),
    ]
