from lupanes.views.customer import (
    CustomerDeliveryNoteCurrentMonthArchiveView,
    CustomerDeliveryNoteMonthArchiveView, DashboardView,
    DeliveryNoteCreateView, DeliveryNoteDeleteView, DeliveryNoteUpdateView,
    NotifyMissingProductView)
from lupanes.views.manager import (CustomerListView,
                                   DeliveryNoteBulkCreateView,
                                   DeliveryNoteBulkUpdateView,
                                   DeliveryNoteBulkDeleteView,
                                   DeliveryNoteCurrentMonthArchiveView,
                                   DeliveryNoteMonthArchiveView,
                                   DeliveryNoteSummaryView,
                                   ProductSummaryView)
from lupanes.views.product import (ProductAjaxView, ProductCreateView,
                                   ProductListView, ProductNewPriceView,
                                   ProductUpdateView)
from lupanes.views.grouporder import (GroupOrderCreateView,
                                      GroupOrderDetailView,
                                      GroupOrderListView,
                                      GroupOrderMineView,
                                      GroupOrderSubmitView)

__all__ = [
    "GroupOrderCreateView",
    "GroupOrderDetailView",
    "GroupOrderListView",
    "GroupOrderMineView",
    "GroupOrderSubmitView",
    "DashboardView",
    "DeliveryNoteBulkCreateView",
    "DeliveryNoteBulkUpdateView",
    "DeliveryNoteBulkDeleteView",
    "CustomerDeliveryNoteCurrentMonthArchiveView",
    "CustomerDeliveryNoteMonthArchiveView",
    "CustomerListView",
    "DeliveryNoteMonthArchiveView",
    "DeliveryNoteCreateView",
    "DeliveryNoteCurrentMonthArchiveView",
    "DeliveryNoteDeleteView",
    "DeliveryNoteUpdateView",
    "DeliveryNoteSummaryView",
    "ProductSummaryView",
    "NotifyMissingProductView",
    "ProductAjaxView",
    "ProductCreateView",
    "ProductListView",
    "ProductNewPriceView",
    "ProductUpdateView",
]
