# Generated by Django 4.2.1 on 2023-06-09 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("lupanes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliverynote",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="registered_notes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
