# Generated by Django 3.2.19 on 2023-11-04 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lupanes', '0002_deliverynote_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverynote',
            name='sheet_number',
            field=models.CharField(blank=True, default='', max_length=6, verbose_name='Nº de hoja'),
        ),
    ]
