# Generated by Django 3.2.19 on 2026-06-15 22:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lupanes', '0003_deliverynote_sheet_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('producer_name', models.CharField(max_length=200, verbose_name='Productor')),
                ('description', models.TextField(blank=True, default='', verbose_name='Descripción')),
                ('closing_date', models.DateTimeField(verbose_name='Fecha de cierre')),
                ('estimated_delivery_date', models.DateField(blank=True, null=True, verbose_name='Fecha estimada de entrega')),
                ('paid_in_albaranes', models.BooleanField(default=False, verbose_name='El pago se registra en albaranes')),
                ('status', models.CharField(choices=[('open', 'Abierto'), ('closed', 'Cerrado'), ('ordered', 'Pedido al productor'), ('arrived', 'Recibido')], default='open', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('arrived_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='group_orders_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GroupOrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Producto')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Precio')),
                ('unit', models.CharField(blank=True, default='', max_length=32, verbose_name='Unidad')),
                ('notes', models.CharField(blank=True, default='', max_length=255, verbose_name='Notas')),
                ('group_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='lupanes.grouporder')),
            ],
        ),
        migrations.CreateModel(
            name='GroupOrderLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Cantidad')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='group_order_line_items', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='lupanes.grouporderproduct')),
            ],
            options={
                'unique_together': {('product', 'customer')},
            },
        ),
    ]
